backend:
  name: git-gateway
  repo: liquidvisual/netlifycms-test # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

display_url: https://jovial-davinci-0a9047.netlify.com
media_folder: "src/assets/img/content" # Folder where user uploaded files should go
public_folder: "/assets/img/content"
# publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit # update
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "suburbs"
        label: "Cambpbelltown Suburbs"
        file: "_data/suburbs.yml"
        description: "Serviceable Suburbs (for SEO)"
        fields:
          - name: suburbs
            label: Suburbs
            label_singular: "Suburb"
            widget: list
            fields:
              - { name: "title", label: "Name",  widget: "string" }
    # - name: "general"
    #   label: "Site Settings"
    #   file: "_data/settings.yml"
    #   description: "General Site Settings"
    #   fields:
    #     - { label: "Global title", name: "site_title", widget: "string"}
    #     - label: "Post Settings"
    #       name: posts
    #       widget: "object"
    #       fields:
    #         - { label: "Number of posts on frontpage", name: front_limit, widget: number }
    #         - { label: "Default Author", name: author, widget: string }
    #         - { label: "Default Thumbnail", name: thumb, widget: image, class: "thumb" }

  - name: "pages"
    label: "Pages"
    delete: false
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: "home"
        file: "src/_pages/home.md"
        fields:
          - { name: "layout", label: "Layout", widget: "hidden", default: "base__homepage"}
          - { name: "title", label: "Title", widget: "string", default: "Homepage" }
          - { name: "permalink", label: "Permalink", widget: "hidden", default: "/" }
          - { name: "regenerate", label: "Regenerate", widget: "hidden", default: true }
          - { name: "hero_title", label: "Hero Title", widget: "string", default: "Hero Ipsum"}
          - { name: "hero_body", label: "Hero Body", widget: "markdown" }
          - { name: "body", label: "Body", widget: "markdown", buttons: ["bold", "italic", "h2", "h3", "h4", "h5", "h6"] }
