backend:
  name: git-gateway
  repo: liquidvisual/netlifycms-test # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

#publish_mode: editorial_workflow
media_folder: "src/assets/img/content" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit # update
  - label: "Pages"
    name: "pages"
    delete: false
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: "home"
        file: "src/_pages/home.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "base__homepage"}
          - { label: "Title", name: "title", widget: "string", default: "Homepage" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - { label: "Regenerate", name: "regenerate", widget: "hidden", default: true }
          - { label: "Hero Title", name: "hero_title", widget: "string", default: "Hero Ipsum"}
          - { label: "Hero Body", name: "hero_body", widget: "markdown" }
          - { label: "Your badass body text", name: "body", widget: "markdown", buttons: ["bold", "italic"] }
