backend:
  name: git-gateway
  repo: liquidvisual/netlifycms-test # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

display_url: https://jovial-davinci-0a9047.netlify.com
media_folder: "src/assets/img/content" # Folder where user uploaded files should go
public_folder: "/assets/img/content"
# publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit # update
  - name: "settings"
    label: "Settings"
    description: >
          The description is a great place for tone setting, high level information, and editing
          guidelines that are specific to a collection.
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "suburbs"
        label: "Suburbs"
        file: "src/_data/suburbs.yml"
        description: >
              SEO area to add your stuff
        fields:
          - name: suburbs
            label: Suburbs
            label_singular: Suburbs
            widget: list
            fields:
              - { name: "title", label: "Name",  widget: "string" }

  - name: "pages"
    label: "Pages"
    delete: false
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: "home"
        file: "src/_pages/home.md"
        create: true
        fields:
          - { name: "layout", label: "Layout", widget: "hidden", default: "base__homepage"}
          - { name: "title", label: "Title", widget: "string", default: "Homepage" }
          - { name: "permalink", label: "Permalink", widget: "hidden", default: "/" }
          - { name: "regenerate", label: "Regenerate", widget: "hidden", default: true }
          - { name: "hero_title", label: "Hero Title", widget: "string", default: "Hero Ipsum"}
          - { name: "hero_body", label: "Hero Body", widget: "markdown" }
          - { name: "body", label: "Body", widget: "markdown", buttons: ["bold", "italic", "h2", "h3", "h4", "h5", "h6"] }

      # - label: "Standard Page"
      #   name: "standard_page"
      #   description: "This is the bomb diggity, work?"
      #   folder: "src/_pages"
      #   create: true
      #   fields:
      #     - { name: "layout", label: "Layout", widget: "hidden", default: "base__homepage"}
      #     - { name: "title", label: "Title", widget: "string", default: "Standard Page" }
      #     - { name: "permalink", label: "Permalink", widget: "hidden", default: "/" }
