backend:
  name: git-gateway
  repo: liquidvisual/netlifycms-test # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

publish_mode: editorial_workflow
media_folder: "src/assets/img/content" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit # update
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/_pages/home.md"
        name: "home"
        label: "Homepage"
        # folder: "src/_pages/"
        # create: false
        # slug:
        fields:
          - {label: "Title", name: "title", widget: "string" }
          - {label: "Your badass body text", name: "body", widget: "markdown" }
          - {label: "Hero Title", name: "hero_title", widget: "string", default: "Hero Ipsum"}
          - {label: "Hero Body", name: "hero_body", widget: "markdown" }
